language: python
env:
    - TOXENV=py36_pytest_3.1.0
    - TOXENV=py36_pytest_latest
    - TOXENV=py37_pytest_3.1.0
    - TOXENV=py37_pytest_latest
install:
    - travis_retry pip install tox
script:
    - travis_retry tox
